# Generated by Django 6.0.3 on 2026-03-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nombre_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_billets', models.IntegerField()),
                ('nom_client', models.CharField(max_length=100)),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.representation')),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='technologies',
            field=models.ManyToManyField(to='core.technologie'),
        ),
        migrations.AddField(
            model_name='film',
            name='technologies',
            field=models.ManyToManyField(to='core.technologie'),
        ),
    ]
